# Release Drafter configuration
# Docs: https://github.com/release-drafter/release-drafter

name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "Bug Fixes"
    labels:
      - "bug"
      - "fix"
  - title: "Documentation"
    labels:
      - "docs"
  - title: "Maintenance"
    labels:
      - "chore"
      - "refactor"
      - "maintenance"
      - "ci"
  - title: "Other"
    labels:
      - "*"

change-template: "- $TITLE (#$NUMBER) @$AUTHOR"

template: |
  ## Summary
  $CHANGES

  ## Contributors
  $CONTRIBUTORS
