# Release Drafter configuration
# Docs: https://github.com/release-drafter/release-drafter

name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "8a1 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "41b Bug Fixes"
    labels:
      - "bug"
      - "fix"
  - title: "4da Documentation"
    labels:
      - "docs"
  - title: "9f9 Maintenance"
    labels:
      - "chore"
      - "refactor"
      - "maintenance"
      - "ci"

change-template: "- $TITLE (#$NUMBER) @$AUTHOR"

template: |
  ## Summary
  $CHANGES

  ## Contributors
  $CONTRIBUTORS
